// sidebars.ts
import { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // Updated sidebar to include robotics modules and RAG chatbot
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Robotics Modules',
      items: [
        {
          type: 'category',
          label: 'Module 1: The Robotic Nervous System (ROS 2)',
          items: [{type: 'autogenerated', dirName: 'modules/module-1-ros2'}],
        },
        {
          type: 'category',
          label: 'Module 2: The Digital Twin (Gazebo & Unity)',
          items: [{type: 'autogenerated', dirName: 'modules/module-2-digital-twin'}],
        },
        {
          type: 'category',
          label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
          items: [{type: 'autogenerated', dirName: 'modules/module-3-ai-brain'}],
        },
        {
          type: 'category',
          label: 'Module 4: Vision-Language-Action (VLA)',
          items: [{type: 'autogenerated', dirName: 'modules/module-4-vla'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'AI Applications',
      items: [
        {
          type: 'category',
          label: 'Physical AI & Humanoid Robotics Assistant',
          items: [{type: 'autogenerated', dirName: 'modules/module-5-rag-chatbot'}],
        },
      ],
    },
    {
      type: 'category',
      label: 'Tutorial Basics',
      items: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
    },
    {
      type: 'category',
      label: 'Tutorial Extras',
      items: [{type: 'autogenerated', dirName: 'tutorial-extras'}],
    },
  ],
};

export default sidebars;
